name: Continuous Integration

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-dependencies.outputs.cache-hit }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache Node.js modules
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies if cache missed
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm install

  lint:
    needs: install-dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Run linter
        run: npm run lint